Broken Authentication Lab
adeyosemanputra/pygoat pull request #29
Opened 2021-05-02 09:12 UTC by kUSHAL0601

Created Lab for Broken Authentication, where login can be manipulated because of the use of cookies

2021-05-02 09:37 UTC, adeyosemanputra commented
@kUSHAL0601 it's conflict can you resolve it?

2021-05-02 09:41 UTC, kUSHAL0601 commented
The conflicts need change in the master branch of this repo too... I don't have write access to this repo. It will be easier if you could do it...

2021-05-03 22:03 UTC, kingthorin commented
> The conflicts need change in the master branch of this repo too... I don't have write access to this repo. It will be easier if you could do it...

Actually your PR needs to be updated to account for the latest changes to master.

2021-05-11 13:30 UTC, kUSHAL0601 commented
@adeyosemanputra could you have a look and approve

2021-05-18 00:10 UTC, adeyosemanputra requested changes

2021-05-18 00:10 UTC, adeyosemanputra commented on requirements.txt
> +secrets
when pip install -r requirements.txt module secrets seem error, could you check it?

2021-05-18 05:25 UTC, kUSHAL0601 commented on requirements.txt
> +secrets
Sure.

2021-05-18 05:40 UTC, kUSHAL0601 commented on requirements.txt
> +secrets
Removed secrets since it is an inbuilt module for python

2021-05-21 05:10 UTC, kUSHAL0601 commented
@adeyosemanputra could you have a look once

2021-05-21 11:58 UTC, adeyosemanputra commented
sure @kUSHAL0601 , @pwned-17 will working on it.

2021-05-21 12:03 UTC, merged

2021-05-21 12:23 UTC, pwned-17 commented
Hey @kUSHAL0601 I have merged it and it's working great , I guess we can add your lab as a second lab for Broken Authentication Lab .

2021-05-25 05:09 UTC, adeyosemanputra commented
@@all-contributors please add @kUSHAL0601 for code